name: ui_notifications
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_cursor: ^0.1.3
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.5.0
  flutter_feather_icons: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
  - family: Poppins1
    fonts:
    - asset: fonts/Poppins-Light.ttf


  - family: Poppins2
    fonts:
    - asset: fonts/Poppins-Medium.ttf

  - family: Poppins3
    fonts:
    - asset: fonts/Poppins-Regular.ttf

  - family: Poppins4
    fonts:
    - asset: fonts/Poppins-SemiBold.ttf

  - family: Poppins5
    fonts:
    - asset: fonts/Poppins-Thin.ttf

